name: desafio-eteg-mklvrn

services:
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_eteg_mkvlrn
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
